### PR TITLE
chktex: add test

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by xu-cheng** [comment]
@DomT4 It works.

**Comment by DomT4** [comment]
Thanks @xu-cheng, Nice work. I pinged a few questions on the Travis changes, but nothing major. If we can find a way to feed Travis secure credentials, we might actually be able to bottle the ` tex ` stuff. @mikemcquaid

**Comment by DomT4** [comment]
[This](http://stackoverflow.com/a/18029286) looks promising on secure credentials.

**Comment by xu-cheng** [comment]
>  If we can find a way to feed Travis secure credentials for Bintray, we might actually be able to bottle the tex stuff.

This won't happen. If we store tokens in travis, the PR ci will be auto disabled(you don't want others to run the test and echo all the tokens).

**Comment by DomT4** [comment]
Presumably, there's methods to encrypt credentials to Travis so only Travis can see them. I've seen it done quite a few times to upload remotely to elsewhere, I'm just not super-familiar with how to do it myself yet. Just floating the idea really, since bottles would be nice.

**Comment by xu-cheng** [comment]
> Presumably, there's methods to encrypt credentials to Travis so only Travis can see them. I've seen it done quite a few times to upload remotely to elsewhere, I'm just not super-familiar with how to do it myself yet. Just floating the idea really, since bottles would be nice.

These credentials will be decrypted into `ENV`. So everyone can access them. c.f. http://docs.travis-ci.com/user/encryption-keys/

In fact, I really hope homebrew CI-bot can install basictex. (TeX user base is even larger than X11.)

**Comment by DomT4** [comment]
Travis is just a one-time run, the machine is "different" every build - How would someone decrypt the variable, or at least - How would someone decrypt the variable locally in a way that's different/easier than to hacking me/you/mike/jack/tim/misty/adam/brett/etc and pulling the key from our ` env `? Maybe I'm just being dim there.

**Comment by xu-cheng** [comment]
Travis will decrypt the credentials into `ENV`. so your scripts can use them to do fancy staff. However, this also means a PR user can run `printenv` to echo all credentials during the test. In the result, travis will auto restrain PR test for owners only if you use travis encryption keys function.

**Comment by DomT4** [comment]
Could we detect that? If a user's PR modifies either the Travis script or their formulae contains the word ` "printenv" ` in there somewhere, we halt the build before it goes anywhere? Could we write that into the ` test-bot ` in Homebrew?

**Comment by xu-cheng** [comment]
1. Travis won't allow you to run PR test. So there's nothing you can do. (And how can you run a whitelist in an arbitrary execution environment?).
2.  Travis only supports Maverick for now. You cannot choose the OS version to bottle from.

**Comment by DomT4** [comment]
On 1 I more meant using the ` test bot ` itself to exit hard if someone's formulae includes an expected ` printenv ` command - Since we have the ability to inspect the contents of files on the fly, we could read the file for that command, and exit hard if detected. Was just throwing thoughts around really.

On 2: Fair point. Forgot we're gonna get chained on that. Oh well. Guess being able to even test the tex stuff is better than the status quo, for now.

**Comment by mikemcquaid** [comment]
> In fact, I really hope homebrew CI-bot can install basictex. (TeX user base is even larger than X11.)

I don't agree here and I'm not really up for installing TeX on the bots. X11 is there for mostly legacy reasons (similarly to Java).

**Comment by DomT4** [comment]
@mikemcquaid What do you want to do with this repo and the ` tex ` stuff? Do you want me to migrate it into Homebrew, or do you want to create a new repo, or? Theoretically if you want to move quickly I can tee up PRs to migrate the tex stuff today - We've been discussing it on and off for 4+ months :smile_cat:. No rush though if you're happy to wait; just trying to a timeline on your thoughts on these types of deps.

**Comment by mikemcquaid** [comment]
@DomT4 If you're OK with that let's move it into Homebrew core. I think you should be able to do that? Migrating the formula afterwards would be :+1: too (and adding to search etc.)

**Comment by DomT4** [comment]
@mikemcquaid Migrated :+1:. I managed to kick myself off the admin team in this repo at the same time, because I forgot it wouldn't automatically re-add me as an "owner" :smile_cat:. If you want to re-add me to contrib rights here, happy to keep helping.

**Comment by mikemcquaid** [comment]
@DomT4 Done. Setting up CI now without bottle support.

**Comment by mikemcquaid** [comment]
Ah, duh, Travis. That'l do.

**Comment by DomT4** [comment]
Thanks! Note to self: When migrating repos, don't boot yourself off the team :smile_cat:.

PR in Homebrew/homebrew: https://github.com/Homebrew/homebrew/pull/38855

**Comment by xu-cheng** [comment]
@mikemcquaid Can you give me the access as well? Thanks :smile:

**Comment by DomT4** [comment]
^ Done. I added you to the ` tex ` team. Presumed Mike & co wouldn't have any problems with that, but if they prefer to give us separate teams I've no objections.

**Comment by DomT4** [comment]
I've kicked Travis into testing this again just to make sure it can find the repo still okay now it's been migrated and such. Should be fine, but it's a simple enough way to check.

**Comment by DomT4** [comment]
```
curl: (7) Failed connect to ctan.math.utah.edu:80; Network is unreachable
Error: Download failed on Cask 'basictex' with message: Download failed: http://mirror.ctan.org/systems/mac/mactex/mactex-basic.pkg
```

Kicked it, again. This is why I went with ` cURL ` last time - The Cask got kinda moody with me on a regular basis. Hopefully just an infrequent glitch here.

**Comment by mikemcquaid** [comment]
@xu-cheng You're on the owners team now (not sure why I didn't do that earlier) so have access to everything by default.

**Comment by xu-cheng** [comment]
> You're on the owners team now (not sure why I didn't do that earlier) so have access to everything by default.

:tada: 

> Kicked it, again. This is why I went with cURL last time - The Cask got kinda moody with me on a regular basis. Hopefully just an infrequent glitch here.

This is wried. I run test multiple times today. All of them are fine.

**Comment by DomT4** [comment]
> This is wried. I run test multiple times today. All of them are fine.

The Tex mirror system isn't... great. Just hits issues sometimes on passing to dead mirrors. Passed fine this time, so shouldn't be a huge thing going forwards. Worst case scenario we have to re-do a few builds every now and again, which isn't too much trouble.

Feel free to merge this PR if you like!

**Comment by DomT4** [comment]
> PR in Homebrew/homebrew: Homebrew/homebrew#38855

And PR here: #3

**Pull request closed without merging**
