### PR TITLE
latexila 3.16.2

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
```
gtk3-update-icon-cache: Failed to open file /usr/local/share/icons/HighContrast/.icon-theme.cache : No such file or directory

Warning: The post-install step did not complete successfully

You can try again using `brew postinstall homebrew/tex/latexila`

==> Summary
/usr/local/Cellar/latexila/3.16.2: 152 files, 3.9M
```

**Comment by tschoonj** [comment]
done!

**Comment by tschoonj** [comment]
@DomT4 Could you merge this one in please?

**Comment by DomT4** [comment]
Will do within the next couple hours. Spent this afternoon with family, enjoying some Github free time, heh.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-tex/commit/3ce83d35edf7ee942bff826b30940b33313dcfa9. Thanks @tschoonj.

It'd be nice to work out if postinstall can use `if build.with? "gnome-themes-standard"` instead of `if File.file?`.

**Pull request closed without merging**
