### PR TITLE
latexila 3.16.1 (new formula)

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by dunn** [comment]
:(
```
==> Installing homebrew/tex/latexila dependency: librsvg

==> Downloading https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.9.tar.xz

==> Downloading from https://mirror.umd.edu/gnome/sources/librsvg/2.40/librsvg-2.40.9.tar.xz

/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; OS X 10.9.5) https://mirror.umd.edu/gnome/sources/librsvg/2.40/librsvg-2.40.9.tar.xz -C 0 -o /Library/Caches/Homebrew/librsvg-2.40.9.tar.xz.incomplete --silent

Error: Failed to download resource "librsvg"

Download failed: https://mirror.umd.edu/gnome/sources/librsvg/2.40/librsvg-2.40.9.tar.xz

 [4;31mFAILED[0m
```
If this doesn't need `depends_on :tex`, could it go in the main repository?

**Comment by tschoonj** [comment]
it certainly could go to the main repository, but I thought this one was reserved for all things LaTeX?

either way, it would be pretty useless without LaTeX installed :-)

**Comment by tschoonj** [comment]
@dunn So should I close this PR and open one in homebrew core instead?

**Comment by dunn** [comment]
This piece of software isn't really useful without LaTeX, right? Maybe add `depends_on :tex => :recommended` and leave it here.

**Comment by tschoonj** [comment]
Ok did that

**Comment by tschoonj** [comment]
@dunn had to fix a couple more bugs, but now everything is ok

**Comment by dunn** [comment]
Merged in d4c06b0797bec7305474abd88edfab85ad35abe1, thanks!!

**Pull request closed without merging**
