### PR TITLE
Delete unused formulae

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Delete all homebrew/tex formulae that show no installations since analytics records began.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@dunn @tschoonj Any objections here?

**Comment by tschoonj** [comment]
Nope the only one I maintain here is latexila

**Comment by dunn** [comment]
I guess this is fine.

**Comment by MikeMcQuaid** [comment]
Thanks all.

**Comment by AESM** [comment]
@MikeMcQuaid – I understand the logic behind removing these.  However, as an avid user of ChkTeX through [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter-chktex) & a meticulous creature who wrote a MacOS bootstrapper which utilizes Homebrew to get things up & running, was it absolutely necessary to remove `homebrew/tex/chktex`?

**Comment by MikeMcQuaid** [comment]
@AESM If you still use it we can re-add it.

**Comment by MikeMcQuaid** [comment]
@AESM reverted/readded in 4b01b7a.

**Comment by AESM** [comment]
@MikeMcQuaid – The fact that you are willing to listen to a lone voice is greatly appreciated.  Happy New Year!   :)

**Pull request merged**
