### PR TITLE
texwrapper: migrate from core, add test

### PR DESCRIPTION
**Pull request by L2G**
https://github.com/Homebrew/homebrew/pull/39196

### CODE REVIEW

**Comment by DomT4** [comment]
Xu's comment [from the other thread](https://github.com/Homebrew/homebrew-tex/pull/8#issuecomment-99701445) applies here as well, thanks!

**Comment by L2G** [comment]
On it.

**Comment by L2G** [comment]
Anyone know if there's a way we can add a sample [La]TeX file as a test fixture, but add it to the homebrew/tex tap so as not to "pollute" core (which I have a feeling someone will jump down my throat about if I try it)?

**Comment by DomT4** [comment]
Not to my knowledge. Could be wrong though. If the test fixture was small, I don't think there'd be a major objection from the core. If anyone jumps at you, you can always point them in my direction and blame me :wink:.

**Comment by L2G** [comment]
I'm too gun-shy with bold suggestions in Homebrew right now. I'm going to try to make a small sample LaTeX file and in-line it in the test block somehow.

**Comment by DomT4** [comment]
Any idea rejection is never personal or such - It's just hard to not be somewhat direct when you're having to look through 50+ Issues and PRs a day. The ideas are always appreciated, even if not always accepted.

Remember on our Travis runs you'll have access to all the utilities BasicTeX supplies, and you can use them to help generate test files. You can also add test resources as formulae resources and then stage them in the `testpath` for use.

**Pull request closed without merging**
